"""add timestamps to roles and permissions

Revision ID: 31f3ecb07e02
Revises: c98960e89ca2
Create Date: 2026-08-23 17:22:26.380521

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '31f3ecb07e02'
down_revision: Union[str, Sequence[str], None] = 'c98960e89ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
