"""add level to role

Revision ID: bb0d3011e58f
Revises: 98cf7ad05f64
Create Date: 2026-09-03 20:55:03.461423

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb0d3011e58f"
down_revision: Union[str, Sequence[str], None] = "98cf7ad05f64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "roles",
        sa.Column("level", sa.Integer(), nullable=True),
    )

    roles = sa.table(
        "roles",
        sa.column("name", sa.String()),
        sa.column("level", sa.Integer()),
    )

    op.execute(roles.update().where(roles.c.name == "Admin").values(level=100))

    op.execute(roles.update().where(roles.c.name == "Manager").values(level=50))

    op.execute(roles.update().where(roles.c.name == "User").values(level=10))

    op.alter_column(
        "roles",
        "level",
        existing_type=sa.Integer(),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "level")
    # ### end Alembic commands ###
